on:
  push:
    branches:
    - develop

jobs:
  Tensorflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configuring Environment
        run: |
          pwd
          git clone https://github.com/Research-inc/NeuralNetworkAdapter.git
      - name: Installing packages
        run: pip install tensorflow
      - name: Running Tests.
        run: |
          cd src/tests
          pwd
  PyTorch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configuring Environment
        run: pwd
      - name: Installing packages
        run: pip install torch
      - name: Running Tests.
        run: ls
    
