on:
  push:
    branches:
    - develop

jobs:
  Tensorflow:
    runs-on: ubuntu-latest    
    steps:
      - name: Configuring Environment
        run: |
          pwd
          git clone https://github.com/Research-inc/NeuralNetworkAdapter.git
      - name: Installing packages
        run: pip install tensorflow
      - name: Running Test Device
        run: |
          cd NeuralNetworkAdapter/src/tests
          python3 test_device.py
          pwd
      - name: Running Test Neural Network
        run: |
          cd NeuralNetworkAdapter/src/tests
          python3 test_neural_network.py
          pwd
          
  PyTorch:
    runs-on: ubuntu-latest   
    steps:
      - name: Configuring Environment
        run: |
          pwd
          git clone https://github.com/Research-inc/NeuralNetworkAdapter.git
      - name: Installing packages
        run: pip install torch
      - name: Running Test Device
        run: |
          cd NeuralNetworkAdapter/src/tests
          python3 test_device.py
          pwd
      - name: Running Test Neural Network
        run: |
          cd NeuralNetworkAdapter/src/tests
          python3 test_neural_network.py
          pwd
